### ISSUE TITLE
Raider Faction Turn Order Fix

### ISSUE THREAD

**Issue by Mrveczt** [Tedster59/lwotc#1]
Ever since LWOTC touched workshop, it broke the raider factions (third/fourth faction) from various mods, this might be because LWOTC overwrites Highlander that normally has the functioning turn order.
The fix is extremely simple and has no downside even for people who dont use raider faction mods.

To be pinpoint precise, this is how LWOTC has turn order set up:
```
!PlayerTurnOrder=()
+PlayerTurnOrder=eTeam_XCom
+PlayerTurnOrder=eTeam_TheLost
+PlayerTurnOrder=eTeam_Alien
+PlayerTurnOrder=eTeam_Resistance
+PlayerTurnOrder=eTeam_Neutral
```

This is wrong, because this misses out the eTeam_One and e-Team_Two
This is how it should look like to work

```
[XComGame.X2TacticalGameRuleset]

!PlayerTurnOrder=()
+PlayerTurnOrder=eTeam_XCom
+PlayerTurnOrder=eTeam_TheLost
+PlayerTurnOrder=eTeam_Alien
+PlayerTurnOrder=eTeam_One
+PlayerTurnOrder=eTeam_Two
+PlayerTurnOrder=eTeam_Resistance
+PlayerTurnOrder=eTeam_Neutral
```

This is how my workshop mod made it to fix it [which is here](https://steamcommunity.com/sharedfiles/filedetails/?id=2977257585&searchtext=Raider) this fix is normally contained within Mod Jam itself, but not everyone plays the collection. So i believe this thing should be fixed anyway, given its so simple and took me 2 minutes in SDK to set up. Once this fix gets implemented in the LWOTC itself, i will hide my mod on workshop, given it will be redundant.

**Comment by Tedster59** [comment]
Integrated into beta version 1.03
