### ISSUE TITLE
Find a way to display number of crates on smash and grab prior to infiltrating it

### ISSUE THREAD

**Issue by Mrveczt** [Tedster59/lwotc#13]
One of the dumber mechanics of LW2 is obfuscating how many crates will spawn and how many troops you should send at minimum and it is especially frustrating when the game taunts you by spawning 6 crates when you send 4 guys, or the other way around, 6 dudes, 4 crates.

The static smash and grab (which i prefer, not the stupid crate fetching where the effort vs reward is out of place, concealment be dammed), should just tell the player "Resistance spotted 5 crates that could be stolen" or something like that. So players know they must send atleast 5 soldiers

If the infiltration wont allow 6 people for 6 crates, then atleast this would make a risk/reward scenario player would have to decide on, you either get alot of loot but risk underinfiltration, or play safe and send 4 guys to get 100% and only be able to get 4 boxes.

**Comment by Tedster59** [comment]
No good way to do this, but did make it 5 minimum, and sitrep effect that spawns 7 or 8 that is shown to the player.
