### ISSUE TITLE
Consider reworking will (or more precisely, Psi Offense of Advent) to make Will as a stat actually relevant rather than being a dump stat that does fuckall in tactical layer

### ISSUE THREAD

**Issue by Mrveczt** [Tedster59/lwotc#16]
One of the changes LWOTC did that in retrospective wasnt tuned correctly is the massive shift of will stat to WOTC values. If you compare Will values to LW2/vanilla values, you realize that LWOTC troops barely have half the intended will values. This is OK to make tiring mechanic work, what it doesnt is the actual main inteded will value - giving soldiers a chance of resisting psionic attacks.

Like, LW2 Master Sergeants had will in ranges of +90-100s, Not even MSGT Skirmishers get even remotely close, even if they roll max will NCE base, they max out at like 68 or something like that.

Was like psi offense of enemies slashed by half too ? No it wasnt (Check the wiki) and it has the following consequences on the gameplay:

1. High Will NCE roll means nothing, because not even the high will roll is not enough to stop even the basic psi attacks, high NCE rolls for will also probably means you have garbage other stats
2. Contributes to the absolute counter gameplay, you either get a mind shield and remove psionic attacks entirely as a mechanic, or dont and eat every single psi attack thrown at you, this also makes reaction fire classes way shittier given they will instantly fold to the first mind spin aimed their way unless mind shield. (Which again, gameplay of absolutes isnt exactly the best)
3. Makes all perks and perma sources (like covert ops training) that boost will worthless, Leadership from Officers is the best example, even when maxed out (Which is a big effort and most people will never even max this stat out), you barely can push the will value to what it was in LW2 and at that point, XCOM is past its power creep treshold and will roll anything anyway or have mind shields on everyone.
5. Will PCS is worthless for psi resisting, even the top tier will PCS wont change anything, the only thing it does is to push tiring mechanic further.
6. Contributes to fringe features discoveries that leave a sour taste in players mouths, like that if you get first panicked and MCd on the same turn, the mind controlled soldier gets to act instantly and attack your squad during Sectoids own turn. (As if it was Compulsion from Mod Jam). 

Dont think its some big brain 4D chess mlg move to have will worthless shit stat, Long War 2 for vanilla had psi attacks actually failing from enemy side as actual core feature the game expected to happen and such high will soldiers actually had something going for them. Compared to what it is now only as "Tiring Timer" and high will soldiers probably have garbage other NCE stats that actually matter in tactical. Yes some changes like stock strike were added in LWOTC, but that again contributes to floppy gameplay, even with nerfed psi offense for Advent, stock strike would still have its place given we have enemies like Warlock and Advanced Priests that cannot be disoriented.

Or you know, you might just yeeet the stock strike entirely to make Mind Control, when it does happen, alot more dangerous like it was in LW2, so muchkins on Discord wont be screamin its just "pure XCOM buffs".

**Comment by wdanny69** [comment]
current will values work well for fatigue and does its job decently well imo, easier to adjust enemy psi stats to help adjust for a given goal on what we want average chances to be

**Comment by Mrveczt** [comment]
> current will values work well for fatigue and does its job decently well imo, easier to adjust enemy psi stats to help adjust for a given goal on what we want average chances to be

Yeah, the will itself if OK for fatigue, the psi offense not being adjusted to will values being slashed in half in WOTC is the problem.

**Comment by Tedster59** [comment]
Closing this one since I actually did nerf a ton of psi offense stats to make Will matter
