### ISSUE TITLE
Suggestion : note liberation 4 network tower sweep objective immediately instead of after hacking.

### ISSUE THREAD

**Issue by wdanny69** [Tedster59/lwotc#17]
On the liberation 4 network tower mission, it is a sweep objective but for some reason does not reveal this until AFTER you have accomplished the first objective of hacking the terminal.

This has led players to inadvertently leave the mission assuming that was the only objective only to find out you also needed to clear the enemies.

The suggestion is to immediately reveal the sweep objective to avoid this confusion. This would also not affect the current thinking of progressing the mission as the reinforcement tag would still encourage the player to reach the terminal as they will keep dropping and thus preventing the clear objective.

**Comment by Tedster59** [comment]
Is fixed in my current working branch, change will be part of the next dev build.
