### ISSUE TITLE
Suggestion : Chosen Changes

### ISSUE THREAD

**Issue by wdanny69** [Tedster59/lwotc#19]
These changes occurred during the dev build and i think it would be beneficial to push to the main branch. some may need reconsideration or another balance pass
 
- All chosen lose most armor - armor is basically useless anyway, makes shredder units no longer nescessary against them 
- Combat readiness instead of granting aim grants 10% explosive damage resistance - makes grenade spam not so a viable option against them early game, decrease to chosen's offensive power
- Decreased the overall the HP of M1 chosen - (at legend) assassin goes from 30 hp 2 armor to 27 hp 0 armor, Warlock from 41 hp 1 armor to 36 hp no armor, hunter from 41 HP 1 armor to 39 hp no armor.
- Chosen are now split into 5 tiers, not 4: This makes their progression strength significantly smoother: 
 FL 3-6 : T1 , FL 7-10 : T2  ,  FL 11 - 15 : T3  ,  FL 16 - 19 : T4  ,  FL 20+ : T5 
- chosen training is now 2 turn(?) cooldown significantly reducing the amount of strengths they have but the strengths are overall stronger (may need to look at them)
- sabotage is overall weaker but guaranteed to happen from 50% 
     supply drain to 25% from 75%
     intel drain to 25% from 75%
     scanning site to 5 days from 14
     covert action delay to 5 days from 14
     research sabotage to 4 days from 12
     steal datapads from 2-4 from 5-10
     steal cores to 2-4 from 5-10
     wound increase to 5 days from 10
     fear of chosen applied to 3 soldiers from 10
     wound staff to 15 days from 60
     weapon upgrade sabotage to 3-5 from 8-10
     swapped places with "retribution" action knowledge level, available from the beginning 
     retribution rebel gain reduction to 35% from 30%

**chosen strength changes**
- psychotic rage now +35% damage when under 50% hp
- new strength unbreakable : immune to rupture (t2)
- new strength hero slayer : deal +35% damage against hero classes (t2)
- all seeing on all chosen is t2
- warlock high voltage renamed to mind combustion and now also lower cooldown of mind scorch by 1
- new warlock strength unholy ascension : champion's bonuses are doubled and grant crit immunity (t3)
- new hunter strength sting grenades
- new assassin strength blood bath : harbor wave radius increased by 2 and can grants blood thirst (t3)
- new assassin strength misty madness : mist grenade radius increased by 2 (t2)
- new assassin strength impenetrable : impact compensation gains 1 max stack (t3)
- hunter t3 return fire replaced with trigger bot : when targeted by enemy fire, fire back once a turn with -35% damage penalty but guaranteed to hit (not disabled by burning)

xcom arashi loses brawler but gain 3 crit damage : increases damage more and brawler didn't make sense
darkclaw fatality threshold now 50% instead of 35%

impact compensation to 25% DR up to 4 stacks from 20% up to 3 stacks. this is along with damage reduction changes (may need to find them)

**warlock**
- instantly summons their follower when spawned and mark a champion, this makes them stronger when alone and much quicker
- summon can only be used once a mission and can be used regardless of active enemies from having a cooldown and restriction
- summon one less enemy on all tiers
- champion scales 4/6/8/12/15 from 4/6/8/15, this is just for the new tier
- summons do not disappear and can be looted again
- champions' cd to 3 from 2 : the scamper marking a champion made them much more difficult and this helps adjust
- mind scorch burn chance to 40% from 70% : makes it less threatening without burning immunity

**hunter**
- mobility to 16 from 18
- grapple range reduced about 35%
- loses rfa but gains new ability tracking shot : at the start of the turn, mark a flanked enemy as a free action that lets the first shot against the target to be guaranteed and does not cost an action

chosen's presence decrease the alert level of a mission to 3 from 5 and retal alert level modifier decreased by 2 and terror mission reduced by an additional 1 level : does not change mini retal difficulty but decreases its difficulty without chosen, 

defend haven reinforcements ramp more slowly : fighting the chosen and rescuing rebels already made time a bit tight.

xcom disruptor rifle lose 10 aim but overbearing superiority also grants 20 crit as well, this also makes the chosen strength stronger

**Comment by Tedster59** [comment]
Brought in in the latest beta release
