### ISSUE TITLE
Suggestion : Banish change

### ISSUE THREAD

**Issue by wdanny69** [Tedster59/lwotc#20]
This change was from the dev build and I think it would be beneficial to the dev build.

Banish aim penalty to 25 from 15.

Reapers also lose shredder, holo targeting, impulse, predator, executioner, and aim assist.

Reaper already has a fair amount of aim and makes it harder for them to stack aim by themselves which will help reduce how many shots banish can land as right now it can be very consistent to land up to 6 shots with expanded mag

I believe there was also a bug which was making the banish penalty apply in a weird way but i think that is fixed? might have to find that

**Comment by Tedster59** [comment]
Brought in in the latest beta change.
