### ISSUE TITLE
PCS hacking reward

### ISSUE THREAD

**Issue by boris-mailhe** [Tedster59/lwotc#26]
PCS only appear as top-tier hacking rewards, which makes Basic PCS a much worse risk-reward ratio than any other reward. Suggested fix:
1) Basic PCS is only a low-tier reward
2) Advanced PCS can appear in both tiers, same as Watch List
3) Superior PCS remains top tier only.

**Comment by Tedster59** [comment]
Made this change in 1.1.0 RC1
