### ISSUE TITLE
Make stasis a hostile action so abilities like Avenger, Covering Fire and CCS react to it

### ISSUE THREAD

**Issue by Mrveczt** [Tedster59/lwotc#27]
Title, Stasis is not considered a hostile ability (even when it is, 1 action point super stun that is impossible to ressist with any means in base LWOTC).

It should be, to get more in line with other perks, for example, Priests greatest champion, IS considered a hostile ability so perks like Avenger will shoot at the Priest.

Feels random and i dont think there is any harm to make the ability hostile so defensive perks would react to it and possibly stop it before its actually cast.

**Comment by Tedster59** [comment]
This seems reasonable, my one concern is how it interacts with the perk that allows you to use Stasis on units on your own team as a defensive ability

**Comment by Tedster59** [comment]
I did this at some point on the beta, forget when, so closing this.
