### ISSUE TITLE
Localization changes

### ISSUE THREAD

**Issue by Mrveczt** [Tedster59/lwotc#3]
LWOTC has bunch of perks or items with questionably written perk descriptions, carrying from Pavonis themselves which could be changed, while us, veterans know these things, there is no harm in actually making certain descriptions more informative or more accurate.

What should be changed:

PCS
Combat Awareness - Line should be added that it works on suppression as well, not just overwatch.
Life Support - Instead of saying it ensures bleedouts when fatally shot (which isnt what it really does), it should say that it just increases the overkill HP treshold considerably.
Hyper reactive pupils - Whenever you deem it a bug or feature and the aim soldier gets even when squadmates miss, it should be included in its description if that bug is considered a feature (see my other post)

Perks
Killer Instincs - Should say it increases TOTAL damage after a crit, the description itself sounds like it only increases the critical damage, not the total damage after a crit and this is a big difference in actual game
Trojan - Should include that it never breaks concealment, on kills or even when it fails to kill and just damage its target, it still wont break concealment
Fan Fire - Should say it only costs 1 action point and doesnt even require quickdraw
Run and Gun - Should include that activating run and gun, disables action point gifting abilities like close encounters, generally, these abilities do have it written in the description, but not the run and gun itself.
Hunker Down - Should contain that it does not put out burning, for those who never played base LW2 and jumped from WOTC to LWOTC.

I guess... that is all i can think off...for now, maybe others will know something too

**Comment by Tedster59** [comment]
I like how me refactoring in some of the old commits on the LWoTC beta branch somehow references this.  If you want, provide suggested wordings so I can more easily address them.

**Comment by Mrveczt** [comment]
> I like how me refactoring in some of the old commits on the LWoTC beta branch somehow references this. If you want, provide suggested wordings so I can more easily address them.

**Comment by Mrveczt** [comment]
I made a copy of the localization file itself and attached it with almost all changes done inside, you can just take that, had to zip it up given github doesnt allow .int files to be just uploaded. The only thing you might want to do is to check for some basic grammar but on surface i tried to keep it simple.
Hunker Down and Fan Fire is missing, that seems to be in other files though.

The file you want to replace is within Localization/LW_PerkPack_Integrated
[XComGame.zip](https://github.com/Tedster59/lwotc/files/11541082/XComGame.zip)

**Comment by Tedster59** [comment]
Revised, found a double "that" in one of the descriptions, removed the incorrect updates for Hyperreactive pupils PCS since that was apparently fixed based on looking at code.
