### ISSUE TITLE
Concussion Rocket friendly fire warning

### ISSUE THREAD

**Issue by copyrite** [Tedster59/lwotc#39]
Concussion Rocket displays a friendly fire warning despite not dealing damage or causing mental impairments to allies.

**Comment by Tedster59** [comment]
Hmm, does my new version still not damage allies?

**Comment by copyrite** [comment]
I tested this in Skirmish+ when I first posted this, not sure anymore which cheats I had enabled. I've got another test pending for #40.

**Comment by copyrite** [comment]
Now fired it in my actual campaign; absolutely no effect on my own guys.
