### ISSUE TITLE
Spectre uses vanilla lightning reflexes instead of LW2 LR that everyone else is using

### ISSUE THREAD

**Issue by Mrveczt** [Tedster59/lwotc#4]
This is clearly an oversight, but Spectres in LWOTC still use the base LR, which gives absolute immunity to reaction fire and makes them bypass even guaranteed hits like Gunslinger, or Focus (if you are playing Mod Jam). Spectres are kinda unfun enemy that is everything but predicable if they decide to cast a infirmary time, undodgeable Horror ability, but their balancing is a topic on its own, now its more of a internal consistency issue i posted here.

Either replace it with base lightning reflexes everyone else has or if you want to make Spectres _yet another_ anti-reaction fire enemy, give them shadowstep, which would be slightly more thematic for a nanobot swarm.

**Comment by Tedster59** [comment]
Fixing with OPTC, hopefully this works.
